/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as models from './index';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';

/**
 * An array value.
 */
export class ArrayValue {
  /**
   * Values in the array.
   */
  values?: Array<models.Value>;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(json: any) {
    if (json.values) {
      this.values = [];
      json.values.forEach((element: models.Value) => {
        this.values?.push(new models.Value(element));
      });
    }
  }
}
// eslint-disable-next-line @typescript-eslint/no-namespace
