/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WriteResult } from './writeResult';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';


/**
 * The response for Firestore.Commit.
 */
export class CommitResponse {
    /**
     * The time at which the commit occurred. Any read with an equal or greater `read_time` is guaranteed to see the effects of the commit.
     */
    commitTime?: string;
    /**
     * The result of applying the writes. This i-th write result corresponds to the i-th write in the request.
     */
    writeResults?: Array<WriteResult>;


// eslint-disable-next-line @typescript-eslint/no-explicit-any
    constructor(json: any) {
        if (json.commitTime) {
        this.commitTime = helpers.stringFromTimestampJson(json.commitTime); //[Data format: google-datetime
        }
        if (json.writeResults) {
        this.writeResults = [];
        json.writeResults.forEach((element: WriteResult) => {
            this.writeResults?.push(new WriteResult(element));
        });
        }
  }
}
