/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Write } from './write';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';


/**
 * The request for Firestore.Commit.
 */
export class CommitRequest {
    /**
     * If set, applies all writes in this transaction, and commits it.
     */
    transaction?: string;
    /**
     * The writes to apply. Always executed atomically and in order.
     */
    writes?: Array<Write>;


// eslint-disable-next-line @typescript-eslint/no-explicit-any
    constructor(json: any) {
        if (json.transaction) {
        this.transaction = helpers.stringFromBufferJson(json.transaction); //[Data format: byte]
        }
        if (json.writes) {
        this.writes = [];
        json.writes.forEach((element: Write) => {
            this.writes?.push(new Write(element));
        });
        }
  }
}
