/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as models from './index';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';

/**
 * A filter.
 */
export class Filter {
  /**
   * A composite filter.
   */
  compositeFilter?: models.CompositeFilter;
  /**
   * A filter on a document field.
   */
  fieldFilter?: models.FieldFilter;
  /**
   * A filter that takes exactly one argument.
   */
  unaryFilter?: models.UnaryFilter;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(json: any) {
    if (json.compositeFilter) {
      this.compositeFilter = new models.CompositeFilter(json.compositeFilter);
    }
    if (json.fieldFilter) {
      this.fieldFilter = new models.FieldFilter(json.fieldFilter);
    }
    if (json.unaryFilter) {
      this.unaryFilter = new models.UnaryFilter(json.unaryFilter);
    }
  }
}
// eslint-disable-next-line @typescript-eslint/no-namespace
