/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompositeFilter } from './compositeFilter';
import { FieldFilter } from './fieldFilter';
import { UnaryFilter } from './unaryFilter';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';


/**
 * A filter.
 */
export class Filter {
    /**
     * A composite filter.
     */
    compositeFilter?: CompositeFilter;
    /**
     * A filter on a document field.
     */
    fieldFilter?: FieldFilter;
    /**
     * A filter that takes exactly one argument.
     */
    unaryFilter?: UnaryFilter;


// eslint-disable-next-line @typescript-eslint/no-explicit-any
    constructor(json: any) {
        if (json.compositeFilter) {
        this.compositeFilter = new CompositeFilter(json.compositeFilter);
        }
        if (json.fieldFilter) {
        this.fieldFilter = new FieldFilter(json.fieldFilter);
        }
        if (json.unaryFilter) {
        this.unaryFilter = new UnaryFilter(json.unaryFilter);
        }
  }
}
