/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as models from './index';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';

/**
 * The response for FirestoreAdmin.ListIndexes.
 */
export class GoogleFirestoreAdminV1ListIndexesResponse {
  /**
   * The requested indexes.
   */
  indexes?: Array<models.GoogleFirestoreAdminV1Index>;
  /**
   * A page token that may be used to request another page of results. If blank, this is the last page.
   */
  nextPageToken?: string | null;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(json: any) {
    if (json.indexes) {
      this.indexes = [];
      json.indexes.forEach((element: models.GoogleFirestoreAdminV1Index) => {
        this.indexes?.push(new models.GoogleFirestoreAdminV1Index(element));
      });
    }
    if (json.nextPageToken) {
      this.nextPageToken = json.nextPageToken; //[Data format: ]
    }
  }
}
// eslint-disable-next-line @typescript-eslint/no-namespace
