/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as models from './index';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';

/**
 * The metadata message for google.cloud.location.Location.metadata.
 */
export class GoogleFirestoreAdminV1LocationMetadata {

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(json: any) {
  }
}
// eslint-disable-next-line @typescript-eslint/no-namespace
