/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GoogleFirestoreAdminV1Field } from './googleFirestoreAdminV1Field';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';


/**
 * The response for FirestoreAdmin.ListFields.
 */
export class GoogleFirestoreAdminV1ListFieldsResponse {
    /**
     * The requested fields.
     */
    fields?: Array<GoogleFirestoreAdminV1Field>;
    /**
     * A page token that may be used to request another page of results. If blank, this is the last page.
     */
    nextPageToken?: string;


// eslint-disable-next-line @typescript-eslint/no-explicit-any
    constructor(json: any) {
        if (json.fields) {
        this.fields = [];
        json.fields.forEach((element: GoogleFirestoreAdminV1Field) => {
            this.fields?.push(new GoogleFirestoreAdminV1Field(element));
        });
        }
        if (json.nextPageToken) {
        this.nextPageToken = json.nextPageToken; //[Data format: ]
        }
  }
}
