/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GoogleFirestoreAdminV1Index } from './googleFirestoreAdminV1Index';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';


/**
 * Information about an index configuration change.
 */
export class GoogleFirestoreAdminV1IndexConfigDelta {
    /**
     * Specifies how the index is changing.
     */
    changeType?: GoogleFirestoreAdminV1IndexConfigDelta.ChangeTypeEnum;
    /**
     * The index being changed.
     */
    index?: GoogleFirestoreAdminV1Index;


// eslint-disable-next-line @typescript-eslint/no-explicit-any
    constructor(json: any) {
        if (json.changeType) {
        this.changeType = json.changeType; //[Data format: ]
        }
        if (json.index) {
        this.index = new GoogleFirestoreAdminV1Index(json.index);
        }
  }
}
export namespace GoogleFirestoreAdminV1IndexConfigDelta {
    export type ChangeTypeEnum = 'CHANGE_TYPE_UNSPECIFIED' | 'ADD' | 'REMOVE';
    export const ChangeTypeEnum = {
        CHANGETYPEUNSPECIFIED: 'CHANGE_TYPE_UNSPECIFIED' as ChangeTypeEnum,
        ADD: 'ADD' as ChangeTypeEnum,
        REMOVE: 'REMOVE' as ChangeTypeEnum
    }
}
