/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as models from './index';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';

/**
 * Metadata for google.longrunning.Operation results from FirestoreAdmin.UpdateField.
 */
export class GoogleFirestoreAdminV1FieldOperationMetadata {
  /**
   * The time this operation completed. Will be unset if operation still in progress.
   */
  endTime?: string | null;
  /**
   * The field resource that this operation is acting on. For example: `projects/{project_id}/databases/{database_id}/collectionGroups/{collection_id}/fields/{field_path}`
   */
  field?: string | null;
  /**
   * A list of IndexConfigDelta, which describe the intent of this operation.
   */
  indexConfigDeltas?: Array<models.GoogleFirestoreAdminV1IndexConfigDelta>;
  /**
   * The progress, in bytes, of this operation.
   */
  progressBytes?: models.GoogleFirestoreAdminV1Progress;
  /**
   * The progress, in documents, of this operation.
   */
  progressDocuments?: models.GoogleFirestoreAdminV1Progress;
  /**
   * The time this operation started.
   */
  startTime?: string | null;
  /**
   * The state of the operation.
   */
  state?: GoogleFirestoreAdminV1FieldOperationMetadata.StateEnum;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(json: any) {
    if (json.endTime) {
      this.endTime = helpers.stringFromTimestampJson(json.endTime); //[Data format: google-datetime
    }
    if (json.field) {
      this.field = json.field; //[Data format: ]
    }
    if (json.indexConfigDeltas) {
      this.indexConfigDeltas = [];
      json.indexConfigDeltas.forEach((element: models.GoogleFirestoreAdminV1IndexConfigDelta) => {
        this.indexConfigDeltas?.push(new models.GoogleFirestoreAdminV1IndexConfigDelta(element));
      });
    }
    if (json.progressBytes) {
      this.progressBytes = new models.GoogleFirestoreAdminV1Progress(json.progressBytes);
    }
    if (json.progressDocuments) {
      this.progressDocuments = new models.GoogleFirestoreAdminV1Progress(json.progressDocuments);
    }
    if (json.startTime) {
      this.startTime = helpers.stringFromTimestampJson(json.startTime); //[Data format: google-datetime
    }
    if (json.state) {
      this.state = json.state; //[Data format: ]
    }
  }
}
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace GoogleFirestoreAdminV1FieldOperationMetadata {
  export type StateEnum =  'OPERATION_STATE_UNSPECIFIED'|'INITIALIZING'|'PROCESSING'|'CANCELLING'|'FINALIZING'|'SUCCESSFUL'|'FAILED'|'CANCELLED';
}
