/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';


/**
 * The request for Firestore.ListCollectionIds.
 */
export class ListCollectionIdsRequest {
    /**
     * The maximum number of results to return.
     */
    pageSize?: number;
    /**
     * A page token. Must be a value from ListCollectionIdsResponse.
     */
    pageToken?: string;


// eslint-disable-next-line @typescript-eslint/no-explicit-any
    constructor(json: any) {
        if (json.pageSize) {
        this.pageSize = json.pageSize; 
        }
        if (json.pageToken) {
        this.pageToken = json.pageToken; //[Data format: ]
        }
  }
}
