/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as models from './index';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';

/**
 * A precondition on a document, used for conditional operations.
 */
export class Precondition {
  /**
   * When set to `true`, the target document must exist. When set to `false`, the target document must not exist.
   */
  exists?: boolean;
  /**
   * When set, the target document must exist and have been last updated at that time.
   */
  updateTime?: string | null;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(json: any) {
    if (json.exists) {
      this.exists = json.exists; 
    }
    if (json.updateTime) {
      this.updateTime = helpers.stringFromTimestampJson(json.updateTime); //[Data format: google-datetime
    }
  }
}
// eslint-disable-next-line @typescript-eslint/no-namespace
