/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as models from './index';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';

/**
 * Options for creating a new transaction.
 */
export class TransactionOptions {
  /**
   * The transaction can only be used for read operations.
   */
  readOnly?: models.ReadOnly;
  /**
   * The transaction can be used for both read and write operations.
   */
  readWrite?: models.ReadWrite;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(json: any) {
    if (json.readOnly) {
      this.readOnly = new models.ReadOnly(json.readOnly);
    }
    if (json.readWrite) {
      this.readWrite = new models.ReadWrite(json.readWrite);
    }
  }
}
// eslint-disable-next-line @typescript-eslint/no-namespace
