/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as models from './index';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';

/**
 * The response for Firestore.Write.
 */
export class WriteResponse {
  /**
   * The time at which the commit occurred. Any read with an equal or greater `read_time` is guaranteed to see the effects of the write.
   */
  commitTime?: string | null;
  /**
   * The ID of the stream. Only set on the first message, when a new stream was created.
   */
  streamId?: string | null;
  /**
   * A token that represents the position of this response in the stream. This can be used by a client to resume the stream at this point. This field is always set.
   */
  streamToken?: string | null;
  /**
   * The result of applying the writes. This i-th write result corresponds to the i-th write in the request.
   */
  writeResults?: Array<models.WriteResult>;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(json: any) {
    if (json.commitTime) {
      this.commitTime = helpers.stringFromTimestampJson(json.commitTime); //[Data format: google-datetime
    }
    if (json.streamId) {
      this.streamId = json.streamId; //[Data format: ]
    }
    if (json.streamToken) {
      this.streamToken = helpers.stringFromBufferJson(json.streamToken); //[Data format: byte]
    }
    if (json.writeResults) {
      this.writeResults = [];
      json.writeResults.forEach((element: models.WriteResult) => {
        this.writeResults?.push(new models.WriteResult(element));
      });
    }
  }
}
// eslint-disable-next-line @typescript-eslint/no-namespace
