/* eslint-disable prettier/prettier */
/**
 * Cloud Firestore API
 * Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as models from './index';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as helpers from '../helpers';

/**
 * The request for Firestore.Write. The first request creates a stream, or resumes an existing one from a token. When creating a new stream, the server replies with a response containing only an ID and a token, to use in the next request. When resuming a stream, the server first streams any responses later than the given token, then a response containing only an up-to-date token, to use in the next request.
 */
export class WriteRequest {
  /**
   * Labels associated with this write request.
   */
  labels?: { [key: string]: string; };
  /**
   * The ID of the write stream to resume. This may only be set in the first message. When left empty, a new write stream will be created.
   */
  streamId?: string | null;
  /**
   * A stream token that was previously sent by the server. The client should set this field to the token from the most recent WriteResponse it has received. This acknowledges that the client has received responses up to this token. After sending this token, earlier tokens may not be used anymore. The server may close the stream if there are too many unacknowledged responses. Leave this field unset when creating a new stream. To resume a stream at a specific point, set this field and the `stream_id` field. Leave this field unset when creating a new stream.
   */
  streamToken?: string | null;
  /**
   * The writes to apply. Always executed atomically and in order. This must be empty on the first request. This may be empty on the last request. This must not be empty on all other requests.
   */
  writes?: Array<models.Write>;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  constructor(json: any) {
    if (json.labels) {
      this.labels = json.labels;
    }
    if (json.streamId) {
      this.streamId = json.streamId; //[Data format: ]
    }
    if (json.streamToken) {
      this.streamToken = helpers.stringFromBufferJson(json.streamToken); //[Data format: byte]
    }
    if (json.writes) {
      this.writes = [];
      json.writes.forEach((element: models.Write) => {
        this.writes?.push(new models.Write(element));
      });
    }
  }
}
// eslint-disable-next-line @typescript-eslint/no-namespace
